FORMAT: X-1A
HOST: http://www.newscooptest.com/

#Newscoop

# Group Article related resources

##Article types [/articleTypes]
+ Model (application/json)

    + Headers
    
            Location: /articleTypes

    + Body
    
            {
                0: "page",
                1: "news",
                2: "scoop",
                3: "ticker"
            }
            

### Retrieve [GET]
Retrieve all available Article Types
+ Response 200
[Article types][]

##Article type [/articleTypes/{id}]
+ Parameters
    + id (required, number, `2`) ... Id of an Article Type.
        
+ Model (application/json)

    + Headers
    
            Location: /articleTypes/{id}

    + Body
    
            {
                "name": "news",
                "fields": {
                    "title": "text"
                    "lead": "text",
                    "content": "wysiwyg"
                }
            }

### Retrieve an Article Type [GET]
Retrieve a specific Article type
+ Response 200
[Article type][]

### Update an Article Type [PATCH]
+ Request Update Article Type (application/json)
[Article type][]

+ Response 200
[Article type][]

### Replace an Article Type [PUT]
+ Request Replace Article Type (application/json)
[Article type][]

+ Response 200
[Article type][]
    
### Delete an Article Type [DELETE]
+ Response 204

##Article [/articles/{id}/{language}]
+ Parameters
    + id (required, number, `2`) ... Id of an Article Type.
    + language (optional, number, `1`) ... Id of a Language
        
+ Model (application/json)

    + Headers
    
            Location: /articles/{id}/{language}

    + Body
    
            {
                "title": "foo bar baz",
                "languageId": 1,
                "publicationId": 3,
                "issueId": 18,
                "sectionId": 2,
                // the articleType is custom
                "articleType": "page",
                "fields": {
                    // these depend on the chosen articleType
                    }
                }
                
### Insert [POST]
+ Request Insert (application/json)
[Article][]
    
+ Response 201
[Article][]
    
### Update [PATCH]
+ Request Update (application/json)
[Article][]

+ Response 200
[Article][]

### Replace [PUT]
+ Request Replace (application/json)
[Article][]

+ Response 200
[Article][]
            
### Delete [DELETE]
+ Response 204


##ArticleNews [/articles/1/1]
This is an Example Article using the ArticleType News
+ Model (application/json)

    + Headers
    
            Location: /articles/1/1

    + Body
    
            {
                "title": "foo bar baz",
                "languageId": 1,
                "publicationId": 1,
                "issueId": 1,
                "sectionId": 1,
                "articleType": "news",
                "fields": {
                        "teaser":"Lorem ipsum dolar amet"
                    }
                }

### Retrieve [GET]
+ Response 200
[ArticleNews][]


##Featured Articles [/articles-lists/{id}]
+ Parameters
    + id (required, number, `2`) ... Id of a Featured Article list
        
+ Model (application/json)

    + Headers
    
            Location: /articles-lists/{id}

    + Body
    
            {
                "title": "foo bar",
                "languageId": 1
            }
                
### Retrieve [GET]
+ Response 200
[Featured Articles][]

### Insert [POST]
+ Request Insert new Featured Article list (application/json)
[Featured Articles][]

+ Response 201
[Featured Articles][]
            
### Replace [PUT]
+ Request Insert new Featured Article list (application/json)
[Featured Articles][]

+ Response 200
[Featured Articles][]
            
### Delete [DELETE]
+ Response 204


# Group Comments

##Comment [/comment/{article}/{language}/{id}]
+ Parameters
    + id (required, number, `8`) ... Id of a Comment
    + article (required, number, `2`) ... Id of an Article
    + language (required, number, `1`) ... Id of a Language
        
+ Model (application/json)

    + Headers
    
            Location: /comments/{article}/{language}/{id}

    + Body
    
            {
                "content": "foo bar baz",
                "commenter": {
                    "name": "foo baz"
                    "email": "foo@example.org"
                }
            }

### Retrieve a Comment [GET]
+ Response 200
[Comment][]

### Insert a Comment [POST]
+ Request Insert (application/json)
[Comment][]

+ Response 201
[Comment][]

### Delete a Comment [DELETE]
+ Response 204

# Group Topics

##Topic [/topics/{id}/{language}]
+ Parameters
    + id (required, number, `8`) ... Id of a Comment
    + language (required, number, `1`) ... Id of a Language
        
+ Model (application/json)

    + Headers
    
            Location: /topics/{id}/{language}

    + Body
    
            {
                "name": "foo bar",
                "languageId": 1
            }

### Retrieve a Topic [GET]
+ Response 200
[Topic][]

### Insert a new Topic [POST]
+ Request insert (application/json)
[Topic][]

+ Response 201
[Topic][]

### Replace a Topic [PUT]
+ Request Replace (application/json)
[Topic][]

+ Response 200
[Topic][]

### Rename a Topic [PATCH]
+ Request Rename (application/json)

        {
            "name": "baz"
        }

+ Response 200

        {
            "name": "baz",
            "languageId": 1
        }
        
### Delete a Topic [DELETE]
+ Response 204